apiVersion: v1
kind: Service
metadata:
  name: rails-service
  labels:
    app: rails
spec:
  selector:
    app: rails
  ports:
    - name: rails
      protocol: TCP
      port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rails
    spec:
      volumes:
      - name: app-volume
        hostPath:
            path: /Users/takeohiroaki/app/rails
            type: Directory
      containers:
      - name: rails
        image: rails
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-volume
          mountPath: /app
        command:
          - tail
          - -f
          - /dev/null

