apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-hostpath-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/takeohiroaki/data/mysql
